### ISSUE TITLE
support `view` action in js sdk

### ISSUE THREAD

**Issue by Yaiba** [trufnetwork/kwil-js#11]
kwilteam/kuneiform#13

**Comment by KwilLuke** [comment]
Is this a change needed for styling in the IDE? The JSK SDK does not currently accept raw kuneiform, only kuneiform parsed to json.

**Comment by Yaiba** [comment]
the process in SDK to execute an action:

* get database schema
* base on action mutability, call tx or auth_call service

Note: view action need signature

**Comment by Yaiba** [comment]
@KwilLuke  is this WIP?

**Comment by KwilLuke** [comment]
It is complete, but I haven't closed the issue because I haven't merged to main branch. Waiting for view to go live before merging to main. @Yaiba
