### ISSUE TITLE
Add validation for .call() endpoint

### ISSUE THREAD

**Issue by KwilLuke** [trufnetwork/kwil-js#33]
Add a validation that checks if a signer is required and if it has been provided when the developer uses the .call() endpoint.

**Comment by Yaiba** [comment]
Probably delay the implementation on this, once we have new gateway, this is not issue

**Comment by KwilLuke** [comment]
Right now the backend will reject the request.

What I am thinking of adding is an SDK check. It will check if the `auxiliaries` and see if there is `must_sign`.

@Yaiba is `must_sign` going away with the new gateway project?

**Comment by Yaiba** [comment]
For now the sdk's functionality is complete I think, as long as you think the user should know if an action need sign or not.

Yeah `must_sign` will be gone, with new gateway, you'll go to an endpoint to authenticate yourself, then you can call any `view` action.

**Comment by KwilLuke** [comment]
Good to know. I will close this issue then.
