### ISSUE TITLE
Have a way to not produce a warning when explicitly passing in a placeholder value for `chainId` discovery

### ISSUE THREAD

**Issue by pkoch** [trufnetwork/kwil-js#75]
# Context

In order to not burden our users with having to configure `chainId` explicitly (especially since they use a bunch of env), we do this little dance:
```typescript
  static async init({
    nodeUrl = KwilWrapper.defaults.kwilProvider,
    dbId = KwilWrapper.defaults.dbId
  }) {
    console.warn("Discovering chainId. This might generate a warning.");
    const kwil = new WebKwil({ kwilProvider: nodeUrl, chainId: "" });
    const chainId = (await kwil.chainInfo()).data?.chain_id ?? KwilWrapper.defaults.chainId;

    // This assumes that nobody else created a db named "idos".
    // Given we intend to not let db creation open, that's a safe enough assumption.
    const dbId_ =
      (await kwil.listDatabases()).data?.filter(({ name }) => name === "idos")[0].dbid || dbId;

    return new KwilWrapper({ nodeUrl, dbId: dbId_, chainId });
  }
```

However, we're passing in `""` for `chainId` on this throw-away `WebKwil`, and that make it (rightly so) complain. As far as I can tell the warning comes from: https://github.com/idos-network/kwil-js/blob/c12d441354af6521a8f71669e9851e01422caadb/src/client/kwil.ts#L348

Having this warning come from kwil-js makes us have to add our own warning to assuage people who look into the console. :sweat_smile:

# Desired behavior

Have a way to signal to kwil-js that "I don't want to be pinned to a specific chainId, and I just want to use whatever is on the provider". This removes the burden for folks who don't care about this specific assurance, and allows folks (like us) that want to discover the chainId with a first call to the provider.

# Suggested implementation

Assigning the empty string this specific intention. That would lead to this code:
```ts
  public async chainInfo(): Promise<GenericResponse<ChainInfo>> {
    const info = await this.client.chainInfo();

    if (this.chainId !== "" && info.data?.chain_id !== this.chainId) {
      console.warn(
        `WARNING: Chain ID mismatch. Expected ${info.data?.chain_id}, got ${this.chainId}`
      );
    }

    return info;
  }
```

**Comment by KwilLuke** [comment]
Hey @pkoch,

Thanks for opening an issue! I can definitely see why you would want to be able to control / omit the error message. And you are correct that is where the warning comes from.

The one concern I have with just omitting the warning altogether with `chainId: ""` is that, before submitting a transaction securely, a developer should know that they are using the correct chainId to prevent transaction forwarding (e.g. preventing a malicious node operator from taking a valid transaction on network A and submitting it on network B). So if someone sets an empty string as a placeholder but later forgets to properly set the chain id, we definitely want to warn them.

I think there are two other approaches we could take on this:

### 1. Optional params to `.chainInfo()` to disable warning

We could add an optional argument to the `.chainInfo()` method that makes the warning configurable. Eg:

```typescript
interface ChainInfoOpts {
  disableWarning?: boolean;
}

public async chainInfo(opts?: ChainInfoOpts): Promise<GenericResponse<ChainInfo>> {
  const info = await this.client.chainInfo();

  if (!opts?.disableWarning && info.data?.chain_id !== this.chainId) {
    console.warn(
      `WARNING: Chain ID mismatch. Expected ${info.data?.chain_id}, got ${this.chainId}`
    );
  }

  return info;
}
```

### 2. Make warning respect `config.logging` argument

We can make the warning message respect the configuration on the `config.logging` property on the WebKwil [Constructor](https://docs.kwil.com/docs/sdks/js-ts/apis#constructor). So the implementation would be:

```typescript
public async chainInfo(): Promise<GenericResponse<ChainInfo>> {
    const info = await this.client.chainInfo();

    if (this.config.logging && info.data?.chain_id !== this.chainId) {
      this.config.logger!(
        `WARNING: Chain ID mismatch. Expected ${info.data?.chain_id}, got ${this.chainId}`
      );
    }

    return info;
  }
```

And then, you can turn this message on/off with:

```typescript
new WebKwil({
    kwilProvider: "some_provider",
    chainId: "",
    logging: false / true
});
```

Thoughts on either of these approaches? I would probably lean towards option 1, but am open to ideas.

**Comment by pkoch** [comment]
Thank you! <3
