### ISSUE TITLE
Problem: `NodeKwil` does not respect logout

### ISSUE THREAD

**Issue by KwilLuke** [trufnetwork/kwil-js#76]
Although the `.auth.logout()` API exists on NodeKwil, it does not actually remove the cookie on each subsequent request.

To close this issue, we need to:
1. Stop passing the cookie on call requests after `.logout()` is called.
2. Allow the developer to pass the cookie in NodeKwil request

**Comment by jchappelow** [comment]
I figured that logout response would be handled by deleting the cookie in nodelwil.  Can do that?

**Comment by KwilLuke** [comment]
Yep, that is what I will have to refactor the method to do. Right now, it just relied on the browser's cookie jar to delete the cookie. Should be a pretty simple fix.
